### ISSUE TITLE
UWP Shell Support

### ISSUE THREAD

**Issue by scottkuhl** [TinyStuff/TinyMvvm#24]
Following the getting started but also adding a UWP project throws an exception on startup:

Invalid pointer

Cannot find a resource with the given key: ShellNavigationView.

Works fine in iOS and Android.

**Comment by dhindrik** [comment]
Do you have a StackTrace?

What is NavigationView? Is that one of your views?

I have noticed that sometimes TinyMvvm swallows the real error and says there is a problem with the setup of the Navigation when the real error is the view or ViewModel that it tries to navigate to. Will do some fixes for that in the next version. Have you tried to select that VS should break on all exceptions, even handled exceptions?

**Comment by scottkuhl** [comment]
Here is the StackTrace:

```
Exception has been thrown by the target of an invocation.
   at Xamarin.Forms.Platform.UWP.Platform.<SetCurrent>d__45.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_0(Object state)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
```

Inner Exception:

```
Invalid pointer

Cannot find a resource with the given key: ShellNavigationView.

   at System.Runtime.InteropServices.WindowsRuntime.IMap`2.Lookup(K key)
   at System.Runtime.InteropServices.WindowsRuntime.MapToDictionaryAdapter.Lookup[K,V](IMap`2 _this, K key)
   at System.Runtime.InteropServices.WindowsRuntime.MapToDictionaryAdapter.Indexer_Get[K,V](K key)
   at Xamarin.Forms.Platform.UWP.ShellRenderer..ctor()
```

**Comment by scottkuhl** [comment]
NavigationView is the UWP control that is being used by Xamarin Forms to implement the Shell control.

**Comment by scottkuhl** [comment]
Here is sample code based on the Getting Started document that demonstrates the problem:

https://github.com/scottkuhl/TinyMvvmSampleApp

**Comment by scottkuhl** [comment]
I have finally been able to recreate this issue without including TinyMVVM libraries. I'm not sure what the cause is yet, but I don't think it has anything to do with TinyMVVM.  It seems to be a Xamarin Forms UWP Shell issue.  I think we can close this one.
